services:
  postgres:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432 # Maps port 5432 on the Docker host to port 5432 on the container
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: