services:
  postgres:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432 # Maps port 5432 on the Docker host to port 5432 on the container
    volumes:
      - postgres-data:/var/lib/postgresql/data

  downloader:
    image: mxcoru/abi-downloader:latest
    environment:
      - DOWNLOADER_BASE_DIR=/app/downloader
    ports:
      - 8080:8080
    volumes:
      - ./downloader:/app/downloader

  file-server:
    image: mxcoru/abi-downloader:latest
    ports:
      - 8081:8080
    environment:
      - FILE_SERVER=enabled
      - DOWNLOADER_BASE_DIR=/app/downloader
    volumes:
      - ./downloader:/app/downloader

volumes:
  postgres-data:
